#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# прогоняет eslint и др тесты только для измененных файлов
# npx lint-staged

# npm run build:prod
# npm run lint:ts
# npm run lint:scss
# npm run test:unit
# npm run storybook:build
# npm run test:ui

